name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - preprod
    paths:
      - 'terraform/**'
      - 'ansible/**'
  workflow_dispatch:
  
  # 👇 NOUVEAU BLOC : Écoute le workflow Docker 👇
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR"] # Doit correspondre EXACTEMENT au "name:" du docker-build.yml
    types:
      - completed
    branches:
      - preprod # Se déclenche uniquement si le build venait de la branche preprod

jobs:
  terraform-and-ansible:
    name: 'Terraform Provisioning & Ansible Configuration'
    runs-on: ubuntu-latest
    
    # 👇 SÉCURITÉ : On ne déploie que si le workflow précédent a RÉUSSI 👇
    # (Ou si on lance le script manuellement / via un push sur terraform/ansible)
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    
    env:
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_DOMAIN_NAME: "Default"

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init, Workspace & Apply
        run: |
          cd terraform
          terraform init
          
          # Sélectionne le workspace correspondant à la branche active (main ou preprod), ou le crée s'il n'existe pas
          # Note: Lors d'un workflow_run, github.ref_name contiendra bien la branche d'origine (preprod)
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}
          
          # Exécute l'apply dans le bon workspace
          terraform apply -auto-approve

      # --- ÉTAPE PASSERELLE : RÉCUPÉRATION DE L'IP ---
      - name: Extraction de l'IP du serveur
        id: get-ip
        run: |
          cd terraform
          VM_IP=$(terraform output -raw instance_ip)
          echo "TARGET_IP=$VM_IP" >> $GITHUB_ENV

      # --- ÉTAPE ANSIBLE ---
      - name: Installation d'Ansible sur le runner GitHub
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configuration de la clé SSH privée
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          sleep 10
          ssh-keyscan -H ${{ env.TARGET_IP }} >> ~/.ssh/known_hosts

      - name: Exécution du Playbook Ansible
        run: |
          ansible-playbook -i "${{ env.TARGET_IP }}," \
            -u debian \
            --private-key ~/.ssh/id_rsa \
            -e "ghcr_username=${{ github.actor }} ghcr_password=${{ secrets.GHCR_PAT }}" \
            ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
