on:
  push:
    branches:
      - main
      - preprod
    paths:
      - 'src/**'
      - 'Dockerfile'

# ...

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Tags pour la production (branche main)
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=V${{ github.run_number }},enable=${{ github.ref == 'refs/heads/main' }}
            
            # Tags pour la préproduction (branche preprod)
            type=raw,value=preprod-latest,enable=${{ github.ref == 'refs/heads/preprod' }}
            type=raw,value=preprod-V${{ github.run_number }},enable=${{ github.ref == 'refs/heads/preprod' }}
            
            # Tag SHA commun
            type=sha
